### ISSUE TITLE
Requirements outdated

### ISSUE THREAD

**Issue by ringods** [kentr/pattern-lab-starterkit-twig-bootstrap4#6]
Patternlab moved to a monorepo setup. Allmost all separate repositories are moved into https://github.com/pattern-lab/patternlab-node/

They also marked Patternlab PHP as a community effort:

| TL;DR Officially declare the authoritative representation of the Pattern Lab spec to be Pattern Lab Node. Signal our intent to deprecate and place Pattern Lab PHP to be under community maintenance only.

Source: https://github.com/pattern-lab/the-spec/issues/37

You should switch to a full NodeJS setup. I have a Pull Request pending which updates the Twig engine to a maintained Twig library in 100% Javascript:
https://github.com/pattern-lab/patternlab-node/pull/1135

Please update your requirements to `@patternlab/engine-twig` in your `package.json` file.

**Comment by kentr** [comment]
Last time I checked, [aleksip/plugin-data-transform wasn't available in the NodeJS version of Pattern Lab](https://github.com/aleksip/plugin-data-transform/issues/29).

I use that plugin extensively, so until that's resolved I'll keep using the PHP version.

**Comment by JEltgroth** [comment]
I'm a little bit confused with the engine-twig package.  I'm currently on the PHP version of Patternlab using Twig, but I'm playing around with the node version with engine-twig to test the viability of switching.  I have multiple twig function and filter extensions I've written for use in our current Pattern Library, and I cannot seem to get a single one to work using Twing via engine-twig after re-writing them in the new export class format studied in the main Twing repo.

Reading the Engine Support Level in engine-twig.js, am I to understand that the ability to add custom extensions is not included with this version of pattern-lab and twing? If so, that's disappointing.  If not, I'm struggling to understand how to properly write extensions in my pattern-lab directory that are recognized by this engine.

**Comment by ringods** [comment]
Hello @JEltgroth, if you are referring to extensions as mentioned under the section `Using Extensions` from this page:

https://nightlycommit.github.io/twing/api.html

It might indeed be the case that it isn't supported yet. I definitely didn't test that yet. Can you file a request in the Patternlab project to track this?

https://github.com/pattern-lab/patternlab-node/issues

**Comment by JEltgroth** [comment]
Hi @ringods.  Thanks for the reply.  I've tried the `twing.addExtension()`. As mentioned in the docs, which are rather anaemic on that topic specifically.  Even when importing the TwigEnvironment and Loader in a custom script in order to access that method, there doesn't actually seem to be  a way that I can find/understand in either engine-twig.js or the twing-specific packages to insert custom extensions before patternlab build does its thing. 

You're right, I'll make a request in the main issue board.  I was just hoping someone possibly encountered this already and knew what to do.
